version: "1"
rules:
  - base: master
    upstream: aviperes:master    # change `wei` to the owner of upstream repo
    mergeMethod: hardreset
    assignees: 
        - hashark
    reviewers:
        - hashark        

