language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
sudo: false
script: bash ./devscripts/run_travis_test.sh
notifications:
  email:
    - filippo.valsorda@gmail.com
    - phihag@phihag.de
    - yasoob.khld@gmail.com
#  irc:
#    channels:
#      - "irc.freenode.org#youtube-dl"
#    skip_join: true
addons:
  apt:
    packages:
      - gettext
      - language-pack-zh-hant
