os: linux
dist: xenial
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
  - "pypy"
  - "pypy3"
env:
  - YTDL_TEST_SET=core
  - YTDL_TEST_SET=download
jobs:
  include:
    - name: flake8
      python: 3.8
      install: pip install flake8
      script: flake8 .
    - python: 2.6  # test end of life veersions of Python on end of life distro Trusty
      dist: trusty
      env: YTDL_TEST_SET=core
    - python: 2.6
      dist: trusty
      env: YTDL_TEST_SET=download
    - python: 3.2
      dist: trusty
      env: YTDL_TEST_SET=core
    - python: 3.2
      dist: trusty
      env: YTDL_TEST_SET=download
    - python: 3.3
      dist: trusty
      env: YTDL_TEST_SET=core
    - python: 3.3
      dist: trusty
      env: YTDL_TEST_SET=download
    - python: 3.4
      dist: trusty
      env: YTDL_TEST_SET=core
    - python: 3.4
      dist: trusty
      env: YTDL_TEST_SET=download
    - env: JYTHON=true; YTDL_TEST_SET=core
      dist: trusty
    - env: JYTHON=true; YTDL_TEST_SET=download
      dist: trusty
  fast_finish: true
  allow_failures:
    - env: YTDL_TEST_SET=download
before_install:
  - if [ "$JYTHON" == "true" ]; then ./devscripts/install_jython.sh; export PATH="$HOME/jython/bin:$PATH"; fi
script: ./devscripts/run_tests.sh
